### ISSUE TITLE
It only works vertically

### ISSUE THREAD

**Issue by malipetek** [0326/trimpng#3]
I will try to solve the problem.

**Comment by malipetek** [comment]
~~This behavior is disappeared when a threshold other than 0 is provided in the arguments. 
Like this: 
`trimmer.crop(clipCanvas, { threshold: 1 }).then((trimmedCanvas, widthDif, heightDif) => {
          //do stuff
})`~~

edit: it was working for some other reason. I have no idea now.

**Comment by 0326** [comment]
This bug was fixed, here are the fix, change `height` to `width`:
> https://github.com/0326/trimpng/commit/557e16354a7d46c3e3c4a988a2692d39b2a02636#diff-8511b9280b3fe95be0395cf15f34624aL129
